### PR TITLE
Pretty please make autoload webpack the default in devmode!

### PR DESCRIPTION
**Pull request by MartinMuzatko**

### CODE REVIEW

**Comment by txchen** [comment]
@MartinMuzatko Currently if I run npm run dev, webpack-dev-server will print the url `http://localhost:5555/webpack-dev-server/` on the console, which will work in iframe mode, auto reload is working well.

May I know why do you think inline mode is better than iframe mode?

**Comment by MartinMuzatko** [comment]
Hello!

It appears that this does not work on my linux  machine.
I'll test it again, but it didn't appear to watch filechanges and autoload.
I'll let you know when I know more.

**Comment by txchen** [comment]
I just tested on my linux vm (ubuntu 15.10), it works well (iframe mode)

**Comment by MartinMuzatko** [comment]
Yep, updated everything! Was my bad.

**Pull request closed without merging**
